name: gaze_tracking
description: Gaze Tracking Graphical Interface
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  fluttertoast: ^8.0.9
  web_socket_channel: ^2.2.0
  mdi: ^5.0.0-nullsafety.0
  just_audio: ^0.9.29
  ini: ^2.1.0
  http: ^0.13.5


  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: LaptopInchs
      fonts:
       - asset: lib/assets/fonts/LaptopInchs.ttf
    - family: AspectRatio
      fonts:
        - asset: lib/assets/fonts/AspectRatio.ttf
    - family: CameraOffset
      fonts:
        - asset: lib/assets/fonts/CameraOffset.ttf

  assets:
    - assets/audio/
    - assets/config.ini

